---
title: 'Lab 3: Reducing Crime'
author: "C. Akkineni, A. Thorp, K. Hanna"
date: "November 27, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Stage 1: Draft Report
```{r}
crime = read.csv('crime_v2.csv')
# Delete the 6 empty rows at the end
crime[92:100,]
crime = crime[1:91, ]

# Convert columns to factors and logical.
crime$county = as.factor(crime$county)
crime$year = as.factor(crime$year)
crime$west = as.logical(crime$west)
crime$central = as.logical(crime$central)
crime$urban = as.logical(crime$urban)

# Fix prbconv, convert from factor to numeric
summary(crime$prbconv)
crime$prbconv = as.numeric(crime$prbconv)

# county 193 is duplidated, remove one
crime[crime$county == 193, ]
crime = crime[-c(89), ]

summary(crime)

```

## Variables:

### Target
crmrte  

### Label
county

### Segregates:
density  
west  
central  
urban   
Likely relationship with density  

### Cost of doing crime:
prbconv  
prbpris  
avgsen  
prbarr  
polpc (likely related to prbconv)  



```{r}
plot(crime$crmrte)
```

```{r}
hist(crime$crmrte)
```

```{r}
model1 = lm(crmrte ~ prbarr + polpc + density, data = crime)
(model1$coefficients)

```


## Steps
Leverage (and Influence if required)  
Goodness-of-Fit : AIC  
Endoginaity  
Omitted variable bias  

